# Generated by Django 3.0.3 on 2020-02-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payload', '0003_auto_20200206_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building_id',
        ),
    ]
