# Generated by Django 3.0.3 on 2020-02-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payload', '0004_remove_building_building_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='desctription',
            new_name='description',
        ),
    ]
